### ISSUE TITLE
Plus Level Design

### ISSUE THREAD

**Issue by terminalarch** [infernoplus/InfringeRoyale#3]
This is something that has bugged me for nearly three years at this point.

At the start of Plus - 1, there are 2 brick blocks surrounding a mystery box. Which are fine and can be broken
![image](https://user-images.githubusercontent.com/57570117/169667124-c9e6e408-6ebe-4b00-a8d4-e71d71222fc1.png)<br><br>

However, near the end of the level, there are another 2 brick blocks surrounding a mystery box. Which can NOT be broken
![image](https://user-images.githubusercontent.com/57570117/169667204-2f69e7a2-acf0-47c4-b2d7-847cf312f10a.png)<br>

What I'm wondering is, is this intentional or an oversight?

**Comment by infernoplus** [comment]
Bug for sure lol. There's probably more than a few accidental block placements like that on the maps I made.

**Comment by terminalarch** [comment]
the w
