### ISSUE TITLE
Relating to 60FPS

### ISSUE THREAD

**Issue by terminalarch** [infernoplus/InfringeRoyale#4]
I've been tinkering with the game's framerate and remembered a statement Inferno once said about 60FPS. To me it seems like there aren't any issues, but just so it doesn't bite me in the arse later on, what was the issue?

**Comment by infernoplus** [comment]
Game physics are tied to the framerate so you will need to effectively halve all the physics values, and you will need to send updates to the server at twice the normal rate or simulate physics on the client side (lol)... 

Better option would be to have everything 1 frame behind and have every other frame interpolate halfway... not hard to do but you do introduce a frame of input lag that way which sucks.

**Comment by terminalarch** [comment]
Makes sense, thanks for the response.
